language: python
python:
    - "3.4"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
    - "3.6-dev" # 3.6 development branch
    - "nightly" # 3.7 development branch
    - "pypy3" # pypy3
os:
    - "linux"
    - "osx"
matrix:
  allow_failures:
      - python: "nightly"
      - python: "pypy3"
      - os: "osx"
addons:
  apt:
    packages:
        - pandoc
# command to install dependencies
install:
    - "pip install --upgrade pip" # upgrade to latest pip (needed on py3.4)
    - "pip install zc.buildout"
    - "buildout"
# command to run tests
script: "bin/py.test"
