language: python
python:
    - "3.4"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
addons:
  apt:
    packages:
        - pandoc
# command to install dependencies
install:
    - "pip install --upgrade pip" # upgrade to latest pip (needed on py3.4)
    - "pip install zc.buildout"
    - "buildout"
# command to run tests
script: "bin/py.test"
